/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {
	public static void main(String[] args) {

	}

	static String timeConversion(String s) {
		String[] arr = s.split(":");
		Integer hh = Integer.parseInt(arr[0]);
		Integer mm = Integer.parseInt(arr[1]);
		String AMPM = arr[2].substring(2, arr[2].length());
		Integer ss = Integer.parseInt(arr[2].substring(0, 2));

		if (AMPM.equalsIgnoreCase("AM") && hh.intValue() == 12) {
			hh = 0;
		} else {
			 hh = hh.intValue() + 12 ;
		}
		return hh + ":" + mm + ":" + ss;
	}
}
/*
 * if(AmPm.equals(checkAM) && hh==12) h=0; else if(AmPm.equals(checkPM)&& hh<12)
 * h+=12;
 * 
 * System.out.printf("%02d:%02d:%02d",h,mm,ss); }
 */
